export const SET_DEP_VARS = 'SET_DEP_VARS';
export const CREATE_DEP_VAR = 'CREATE_DEP_VAR';
export const SET_DEP_VAR_NAME = 'SET_DEP_VAR_NAME';

export const ADD_MEASURE = 'ADD_MEASURE';

export const SET_USER = 'SET_USER';
export const LOG_OUT_USER = 'LOG_OUT_USER';

export const SET_SAMPLES = 'SET_SAMPLES';
export const SET_IND_VAR_OPTION_ON_SAMPLE = 'SET_IND_VAR_OPTION_ON_SAMPLE';
export const CREATE_SAMPLE = 'CREATE_SAMPLE';
export const INSERT_SAMPLE = 'INSERT_SAMPLE';

export const SET_REQUESTS = 'SET_REQUESTS';

export const SET_REMINDERS = 'SET_REMINDERS';

export const GO_TO_NEXT_QUESTION = 'GO_TO_NEXT_QUESTION';
export const GO_TO_PREV_QUESTION = 'GO_TO_PREV_QUESTION';
export const RESET_QUESTION_INDEX = 'RESET_QUESTION_INDEX';
export const SET_VALIDITY = 'SET_VALIDITY';

export const SET_MEASURES = 'SET_MEASURES';
export const CREATE_MEASURE = 'CREATE_MEASURE';
export const SET_KIND = 'SET_KIND';
export const SET_UNIT = 'SET_UNIT';
export const SET_SCALE = 'SET_SCALE';
export const SET_SCALE_DESCRIPTION_MIN = 'SET_SCALE_DESCRIPTION_MIN';
export const SET_SCALE_DESCRIPTION_MIDDLE = 'SET_SCALE_DESCRIPTION_MIDDLE';
export const SET_SCALE_DESCRIPTION_MAX = 'SET_SCALE_DESCRIPTION_MAX';
export const ADD_SAMPLE = 'ADD_SAMPLE';
export const ADD_LIST_ITEM = 'ADD_LIST_ITEM';
export const REMOVE_LIST_ITEM = 'REMOVE_LIST_ITEM';
export const SET_MEASURE_NAME = 'SET_MEASURE_NAME';

export const SET_IND_VARS = 'SET_IND_VARS';
export const CREATE_IND_VAR = 'CREATE_IND_VAR';
export const SET_INDVAR_NAME = 'SET_INDVAR_NAME';
export const SET_INDVAR_ACTIONS_PER_TRIAL = 'SET_INDVAR_ACTIONS_PER_TRIAL';
export const SET_INDVAR_NUM_TRIALS = 'SET_INDVAR_NUM_TRIALS';
export const SET_INDVAR_RANDOMIZED = 'SET_INDVAR_RANDOMIZED';
export const ADD_INDVAR_OPTION = 'ADD_INDVAR_OPTION';
export const REMOVE_INDVAR_OPTION = 'REMOVE_INDVAR_OPTION';

export const SET_HYPOTHESIS = 'SET_HYPOTHESIS';
export const SET_CAUSE = 'SET_CAUSE';
export const SET_EFFECT = 'SET_EFFECT';

export const SET_EXPERIMENTS = 'SET_EXPERIMENTS';
export const CREATE_EXPERIMENT = 'CREATE_EXPERIMENT';
export const DELETE_EXPERIMENT = 'DELETE_EXPERIMENT';
export const SET_EXPERIMENT_KIND = 'SET_EXPERIMENT_KIND';
export const SET_ACTIVE = 'SET_ACTIVE';
export const SET_NAME = 'SET_NAME';

export const ADD_DEP_VAR = 'ADD_DEP_VAR';
export const ADD_IND_VAR = 'ADD_IND_VAR';
